chronosphereio/calyptia-charts

charts/fluentd/.helmignore, charts/fluentd/Chart.yaml, charts/fluentd/README.md, charts/fluentd/templates/NOTES.txt, charts/fluentd/templates/_helpers.tpl, charts/fluentd/templates/_pod.tpl, charts/fluentd/templates/clusterrole.yaml, charts/fluentd/templates/clusterrolebinding.yaml, charts/fluentd/templates/daemonset.yaml, charts/fluentd/templates/deployment.yaml, charts/fluentd/templates/files.conf/systemd.yaml, charts/fluentd/templates/fluentd-config-map.yaml, charts/fluentd/templates/serviceaccount.yaml, charts/fluentd/templates/tests/test-connection.yaml, charts/fluentd/values.yaml
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>
=> Support Calyptia flavor of Fluentd helm chart

charts/aggregator/Chart.yaml, charts/aggregator/templates/deployment.yaml, charts/aggregator/values.yaml
Signed-off-by: Jorge Niedbalski <jnr@metaklass.org>
=> release v0.1.6

charts/aggregator/Chart.yaml, charts/aggregator/templates/deployment.yaml, charts/aggregator/values.yaml
Signed-off-by: Jorge Niedbalski <jnr@metaklass.org>
=> make tls a default value

charts/fluentd/Chart.yaml, charts/fluentd/templates/_pod.tpl
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>
=> Upgrade to use Fluentd v1.14.3 image

charts/fluentd/Chart.yaml
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>
=> Upgrade to use Fluentd v1.14.4

charts/aggregator/Chart.yaml, charts/aggregator/values.yaml
* Switches to v0.1.12 of aggregator
=> release v0.1.12 of aggregator

charts/core/Chart.yaml
=> calyptia-core: v0.1.14

charts/core/templates/deployment.yaml
Allow setting the values for tls and tls_verify for core.
=> core: allow setting the values of tls and tls_verify.

charts/core/Chart.yaml
Upgrade default core image to v0.2.0
=> Upgrade default core image to v0.2.0

charts/core/Chart.yaml
Signed-off-by: Jorge Niedbalski <j@calyptia.com>
=> Update to Core release v0.4.0

README.md
Resolves https://github.com/calyptia/cloud/issues/598.
Signed-off-by: Patrick Stephens <pat@calyptia.com>
=> docs: provide YAML only option

README.md, charts/core/Chart.yaml
Add reference on how to setup tags on calyptia/core instances.
Signed-off-by: Jorge Niedbalski <j@calyptia.com>
=> Update docs for tags

charts/core/values.yaml
Increase version of charts/core and add a minor doc change.
Signed-off-by: Jorge Niedbalski <j@calyptia.com>
=> Test change to trigger release 

charts/core/Chart.yaml
Update core version to v0.4.2
Signed-off-by: Jorge Niedbalski <j@calyptia.com>
=> Update core version to v0.4.2

.github/workflows/cron-sync-core.yaml, charts/core/Chart.yaml
Missing update in sed command
Updated for 1.1 releases
=> chart: update version handling

charts/aws-fluent-bit/Chart.yaml, charts/aws-fluent-bit/templates/configmap.yaml
Resolve an issue with the incorrect config map mount.
=> aws: fix incorrect config map

charts/aws-eks-addon/.helmignore, charts/aws-eks-addon/Chart.yaml, charts/aws-eks-addon/templates, charts/aws-eks-addon/values.yaml, charts/aws-eks-addon/values.yaml.json, charts/aws-fluent-bit/templates/_helpers.tpl, charts/aws-fluent-bit/templates/_pod.tpl, charts/aws-fluent-bit/templates/namespace.yaml, charts/aws-fluent-bit/templates/service.yaml
Add initial EKS add-on chart per docs from AWS.
Reuse the existing chart templates but with pre-defined and limited configuration according to JSON schema.
TODO: add testing using ephemera cluster deployments in EKS - will require some tweaking of image pull secrets and service account creation.
=> eks: create add-on chart and configuration

charts/aws-fluent-bit/Chart.yaml, charts/core/Chart.yaml
Resolve failing linting issue on updates.
=> core: fix linting issue with missing maintainer

charts/aws-eks-addon/Chart.yaml, charts/aws-eks-addon/values.yaml
Service account is required to be created for EKS add-on.
=> eks: ensure we create a service account

README.md
Basic command for installing core-operator and core-instance
=> added install instructions for core-operator and core-instance

.github/workflows/lint.yml, .github/workflows/release.yaml
Add fluent chart for the on-prem dependency.
=> workflows: fix missing deps

charts/aws-eks-addon/Chart.yaml, charts/aws-eks-addon/templates/configmap.yaml, charts/aws-eks-addon/values.yaml
fixes token value path
it looks like we have a action enforce commit signature, it's failing because I've used GH ui to edit
=> addon: fix token value path

.github/workflows/lint.yml, .github/workflows/release.yaml
Add missing dependencies for on-prem chart.
=> workflows: add missing dependencies for helm

charts/core/Chart.yaml, charts/core/templates/_helpers.tpl, charts/core/templates/clusterrole.yaml, charts/core/templates/deployment.yaml, charts/core/templates/scc.yaml, charts/core/values.yaml
Add SCC support to Core chart.
Ensure we set the environment variable to use for the SA on daemonsets.
=> core: add SCC support for Openshift

.github/workflows/lint.yml, .mdlrc, README.md, markdownlint.rb
Various issues with latest `ct` releases now resolved but need to update to specific versions.
=> workflows: fix ChartTesting version issues
